services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=shubham@123
      - POSTGRES_DB=dvdrental
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data

       

       